version: '3.8'
services:
  backend:
    build: ./
    image: phizickdocker/server_alg:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - "APP_MODULE=app.app"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
